-- ACCOUNTING
INSERT INTO minors (course_num,subject,minor_name) VALUES ('203','ACCT','ACCOUNTING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('204','ACCT','ACCOUNTING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('100','BUS','ACCOUNTING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('150','ECON','ACCOUNTING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('103','ECON','ACCOUNTING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('301','ACCT','ACCOUNTING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('302','ACCT','ACCOUNTING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('310','ACCT','ACCOUNTING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('311','ACCT','ACCOUNTING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('330','ACCT','ACCOUNTING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('350','ACCT','ACCOUNTING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('401','ACCT','ACCOUNTING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('402','ACCT','ACCOUNTING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('403','ACCT','ACCOUNTING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('404','ACCT','ACCOUNTING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('405','ACCT','ACCOUNTING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('451','ACCT','ACCOUNTING');

-- AFRICAN DIASPORA STUDIES
INSERT INTO minors (course_num,subject,minor_name) VALUES ('242','HIST','AFRICAN DIASPORA STUDIES');

-- AMERICAN STUDIES
INSERT INTO minors (course_num,subject,minor_name) VALUES ('211','ENG','AMERICAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('226','HIST','AMERICAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('227','HIST','AMERICAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('280','ART','AMERICAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('343','MUS','AMERICAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('328','ENG','AMERICAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('340','ENG','AMERICAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('341','ENG','AMERICAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('443','ENG','AMERICAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('340','PHIL','AMERICAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('342','PHIL','AMERICAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('105','POSC','AMERICAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('110','POSC','AMERICAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('300','POSC','AMERICAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('210','POSC','AMERICAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('211','POSC','AMERICAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('212','POSC','AMERICAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('312','POSC','AMERICAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('316','HIST','AMERICAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('320','HIST','AMERICAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('321','HIST','AMERICAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('364','HIST','AMERICAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('201','REST','AMERICAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('154','SPAN','AMERICAN STUDIES');

-- STUDIO ART
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','ART','STUDIO ART');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('110','ART','STUDIO ART');

-- ART HISTORY
INSERT INTO minors (course_num,subject,minor_name) VALUES ('160','ART','ART HISTORY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('180','ART','ART HISTORY');

-- PHOTOGRAPHY
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','ART','PHOTOGRAPHY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('110','ART','PHOTOGRAPHY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('145','ART','PHOTOGRAPHY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('231','ART','PHOTOGRAPHY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('220','ART','PHOTOGRAPHY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('240','ART','PHOTOGRAPHY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('314','ART','PHOTOGRAPHY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('320','ART','PHOTOGRAPHY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('425','ART','PHOTOGRAPHY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('313','ART','PHOTOGRAPHY');

-- GRAPHIC DESIGN
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','ART','GRAPHIC DESIGN');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('231','ART','GRAPHIC DESIGN');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('211','ART','GRAPHIC DESIGN');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('215','ART','GRAPHIC DESIGN');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('315','ART','GRAPHIC DESIGN');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('320','ART','GRAPHIC DESIGN');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('322','ART','GRAPHIC DESIGN');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('323','ART','GRAPHIC DESIGN');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('320','ART','GRAPHIC DESIGN');

-- BIOLOGY
INSERT INTO minors (course_num,subject,minor_name) VALUES ('130','BIOL','BIOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('131','BIOL','BIOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('131','CHEM','BIOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('132','CHEM','BIOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('201','BIOL','BIOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('202','BIOL','BIOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('203','BIOL','BIOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('211','BIOL','BIOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('305','BIOL','BIOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('312','BIOL','BIOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('315','BIOL','BIOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('320','BIOL','BIOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('321','BIOL','BIOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('325','BIOL','BIOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('340','BIOL','BIOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('360','BIOL','BIOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('390','BIOL','BIOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('391','BIOL','BIOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('392','BIOL','BIOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('420','BIOL','BIOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('421','BIOL','BIOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('430','BIOL','BIOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('435','BIOL','BIOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('440','BIOL','BIOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('450','BIOL','BIOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('493','BIOL','BIOLOGY');

-- BUSINESS
INSERT INTO minors (course_num,subject,minor_name) VALUES ('203','ACCT','BUSINESS');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('204','ACCT','BUSINESS');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('103','ECON','BUSINESS');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('104','ECON','BUSINESS');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('320','BUS','BUSINESS');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('301','BUS','BUSINESS');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('340','BUS','BUSINESS');

-- CHEMISTRY
INSERT INTO minors (course_num,subject,minor_name) VALUES ('131','CHEM','CHEMISTRY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('132','CHEM','CHEMISTRY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('211','CHEM','CHEMISTRY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('212','CHEM','CHEMISTRY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('215','CHEM','CHEMISTRY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('216','CHEM','CHEMISTRY');

-- COMMUNICATION
INSERT INTO minors (course_num,subject,minor_name) VALUES ('102','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('110','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('110','MDIA','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('210','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('313','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('410','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('310','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('311','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('411','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('312','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('102','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('203','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('301','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('302','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('325','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('420','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('425','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('102','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('200','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('242','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('236','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('322','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('327','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('331','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('328','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('332','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('345','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('300','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('341','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('342','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('102','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('211','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('212','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('333','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('418','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('419','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('422','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('102','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('242','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('260','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('365','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('445','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('448','COM','COMMUNICATION');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('460','COM','COMMUNICATION');

-- COMPUTER SCIENCE
INSERT INTO minors (course_num,subject,minor_name) VALUES ('120','CMPT','COMPUTER SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('220','CMPT','COMPUTER SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('221','CMPT','COMPUTER SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('205','MATH','COMPUTER SCIENCE');

-- CRIMINAL JUSTICE
INSERT INTO minors (course_num,subject,minor_name) VALUES ('202','CRJU','CRIMINAL JUSTICE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('304','CRJU','CRIMINAL JUSTICE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('370','CRJU','CRIMINAL JUSTICE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('305','CRJU','CRIMINAL JUSTICE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('230','CRJU','CRIMINAL JUSTICE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('235','CRJU','CRIMINAL JUSTICE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('250','CRJU','CRIMINAL JUSTICE');

-- ECONOMICS
INSERT INTO minors (course_num,subject,minor_name) VALUES ('103','ECON','ECONOMICS');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('104','ECON','ECONOMICS');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('130','MATH','ECONOMICS');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('115','MATH','ECONOMICS');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('241','MATH','ECONOMICS');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('303','ECON','ECONOMICS');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('304','ECON','ECONOMICS');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('305','ECON','ECONOMICS');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('310','ECON','ECONOMICS');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('315','ECON','ECONOMICS');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('320','ECON','ECONOMICS');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('321','ECON','ECONOMICS');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('340','ECON','ECONOMICS');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('422','ECON','ECONOMICS');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('432','ECON','ECONOMICS');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('442','ECON','ECONOMICS');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('443','ECON','ECONOMICS');

-- ENGLISH
INSERT INTO minors (course_num,subject,minor_name) VALUES ('180','ENG','ENGLISH');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('270','ENG','ENGLISH');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('150','ENG','ENGLISH');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('325','ENG','ENGLISH');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('227','ENG','ENGLISH');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('241','ENG','ENGLISH');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('349','ENG','ENGLISH');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('229','ENG','ENGLISH');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('310','ENG','ENGLISH');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('349','ENG','ENGLISH');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('350','ENG','ENGLISH');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('451','ENG','ENGLISH');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('320','ENG','ENGLISH');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('321','ENG','ENGLISH');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('340','ENG','ENGLISH');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('341','ENG','ENGLISH');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('355','ENG','ENGLISH');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('363','ENG','ENGLISH');

-- WRITING
INSERT INTO minors (course_num,subject,minor_name) VALUES ('185','ENG','WRITING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('218','ENG','WRITING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('230','ENG','WRITING');

-- CREATIVE WRITING
INSERT INTO minors (course_num,subject,minor_name) VALUES ('280','ENG','CREATIVE WRITING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('218','ENG','CREATIVE WRITING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('310','ENG','CREATIVE WRITING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('311','ENG','CREATIVE WRITING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('380','ENG','CREATIVE WRITING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('382','ENG','CREATIVE WRITING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('392','ENG','CREATIVE WRITING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('490','ENG','CREATIVE WRITING');

-- FASHION MERCHANDISING
INSERT INTO minors (course_num,subject,minor_name) VALUES ('100','FASH','FASHION MERCHANDISING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('265','FASH','FASHION MERCHANDISING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('304','FASH','FASHION MERCHANDISING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('200','FASH','FASHION MERCHANDISING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('245','FASH','FASHION MERCHANDISING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('266','FASH','FASHION MERCHANDISING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('235','FASH','FASHION MERCHANDISING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('295','FASH','FASHION MERCHANDISING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('305','FASH','FASHION MERCHANDISING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('315','FASH','FASHION MERCHANDISING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('355','FASH','FASHION MERCHANDISING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('455','FASH','FASHION MERCHANDISING');

-- PRODUCT DEVELOPMENT
INSERT INTO minors (course_num,subject,minor_name) VALUES ('200','FASH','PRODUCT DEVELOPMENT');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('289','FASH','PRODUCT DEVELOPMENT');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('300','FASH','PRODUCT DEVELOPMENT');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('267','FASH','PRODUCT DEVELOPMENT');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('325','FASH','PRODUCT DEVELOPMENT');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('341','FASH','PRODUCT DEVELOPMENT');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('379','FASH','PRODUCT DEVELOPMENT');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('415','FASH','PRODUCT DEVELOPMENT');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('455','FASH','PRODUCT DEVELOPMENT');

-- PRODUCT DEVELOPMENT
INSERT INTO minors (course_num,subject,minor_name) VALUES ('200','FASH','PRODUCT DEVELOPMENT');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('289','FASH','PRODUCT DEVELOPMENT');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('300','FASH','PRODUCT DEVELOPMENT');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('267','FASH','PRODUCT DEVELOPMENT');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('325','FASH','PRODUCT DEVELOPMENT');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('341','FASH','PRODUCT DEVELOPMENT');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('379','FASH','PRODUCT DEVELOPMENT');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('415','FASH','PRODUCT DEVELOPMENT');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('455','FASH','PRODUCT DEVELOPMENT');

-- FRENCH LANGUAGE STUDIES
INSERT INTO minors (course_num,subject,minor_name) VALUES ('201','FREN','FRENCH LANGUAGE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('202','FREN','FRENCH LANGUAGE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('250','FREN','FRENCH LANGUAGE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('251','FREN','FRENCH LANGUAGE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('305','FREN','FRENCH LANGUAGE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('315','FREN','FRENCH LANGUAGE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('310','FREN','FRENCH LANGUAGE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('311','FREN','FRENCH LANGUAGE STUDIES');

-- GLOBAL STUDIES
INSERT INTO minors (course_num,subject,minor_name) VALUES ('102','ANTH','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('232','ANTH','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('255','ART','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('256','ART','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('202','BUS','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('430','BUS','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('442','BUS','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('305','CMPT','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('325','COM','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('400','COM','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('488','COM','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('350','CRJU','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('377','CRJU','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('440','CRJU','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('150','ECON','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('305','ECON','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('340','ECON','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('432','ECON','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('442','ECON','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','ENSC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('202','ENSC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('201','ENG','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('302','ENG','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('353','ENG','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('370','ENG','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('373','ENG','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('455','FASH','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('206','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('242','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('252','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('255','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('262','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('263','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('267','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('269','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('271','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('274','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('280','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('285','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('313','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('318','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('320','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('349','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('355','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('375','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('326','MDIA','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('422','MDIA','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('212','PHIL','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('301','PHIL','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('325','PHIL','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('340','PHIL','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('111','POSC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('113','POSC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('202','POSC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('213','POSC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('236','POSC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('251','POSC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('285','POSC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('290','POSC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('271','POSC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('280','POSC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('321','POSC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('325','POSC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('350','POSC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('351','POSC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('355','POSC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('222','PSYC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('330','PSYC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('209','REST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('219','REST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('230','REST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('231','REST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('315','REST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('320','REST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('219','SOC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('226','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('227','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('477','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('103','CMPT','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('248','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('249','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('252','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('206','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('242','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('267','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('268','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('269','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('270','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('271','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('273','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('274','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('280','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('313','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('318','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('355','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('375','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('413','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('497','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','FYS','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('120','ENG','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','PHIL','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('226','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('227','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('477','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('248','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('249','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('252','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('206','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('242','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('267','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('268','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('269','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('270','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('271','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('273','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('274','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('280','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('313','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('318','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('355','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('375','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('413','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('497','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('103','ECON','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('110','POSC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','PSYC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('207','PSYC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('318','PSYC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','EDUC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('150','EDUC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('354','EDUC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('355','EDUC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('410','EDUC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('420','EDUC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('464','EDUC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','FYS','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('120','ENG','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','PHIL','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','FYS','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('103','CMPT','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('120','ENG','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('226','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','PHIL','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('226','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('226','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('200','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('200','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('200','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('477','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('413','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('413','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','FYS','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('226','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('120','ENG','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('226','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','PHIL','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('110','POSC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('226','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','EDUC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('110','POSC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('226','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('200','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('200','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('318','PSYC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('207','PSYC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('150','EDUC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('103','ECON','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('477','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('354','EDUC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('355','EDUC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('413','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('464','EDUC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('420','EDUC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('410','EDUC','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('248','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('226','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('227','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('242','HIST','GLOBAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('280','HIST','GLOBAL STUDIES');

-- HUDSON RIVER VALLEY REGIONAL STUDIES
INSERT INTO minors (course_num,subject,minor_name) VALUES ('218','HIST','HUDSON RIVER VALLEY REGIONAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('330','HONR','HUDSON RIVER VALLEY REGIONAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','ENSC','HUDSON RIVER VALLEY REGIONAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('351','HONR','HUDSON RIVER VALLEY REGIONAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('233','ANTH','HUDSON RIVER VALLEY REGIONAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('290','ART','HUDSON RIVER VALLEY REGIONAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('231','ENG','HUDSON RIVER VALLEY REGIONAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('315','ENSC','HUDSON RIVER VALLEY REGIONAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('331','HONR','HUDSON RIVER VALLEY REGIONAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('220','HIST','HUDSON RIVER VALLEY REGIONAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('210','ECON','HUDSON RIVER VALLEY REGIONAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('202','POSC','HUDSON RIVER VALLEY REGIONAL STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('211','POSC','HUDSON RIVER VALLEY REGIONAL STUDIES');

-- INFORMATION TECHNOLOGY
INSERT INTO minors (course_num,subject,minor_name) VALUES ('120','CMPT','INFORMATION TECHNOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('220','CMPT','INFORMATION TECHNOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('221','CMPT','INFORMATION TECHNOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('306','CMPT','INFORMATION TECHNOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('205','MATH','INFORMATION TECHNOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('307','CMPT','INFORMATION TECHNOLOGY');

-- ENTERPRISE COMPUTING
INSERT INTO minors (course_num,subject,minor_name) VALUES ('120','CMPT','ENTERPRISE COMPUTING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('220','CMPT','ENTERPRISE COMPUTING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('315','CMPT','ENTERPRISE COMPUTING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('316','CMPT','ENTERPRISE COMPUTING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('317','CMPT','ENTERPRISE COMPUTING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('451','CMPT','ENTERPRISE COMPUTING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('452','CMPT','ENTERPRISE COMPUTING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('455','CMPT','ENTERPRISE COMPUTING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('456','CMPT','ENTERPRISE COMPUTING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('453','CMPT','ENTERPRISE COMPUTING');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('454','CMPT','ENTERPRISE COMPUTING');

-- INFORMATION SYSTEMS
INSERT INTO minors (course_num,subject,minor_name) VALUES ('120','CMPT','INFORMATION SYSTEMS');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('100','BUS','INFORMATION SYSTEMS');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('230','CMPT','INFORMATION SYSTEMS');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('306','CMPT','INFORMATION SYSTEMS');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('330','CMPT','INFORMATION SYSTEMS');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('308','CMPT','INFORMATION SYSTEMS');

-- ITALIAN
INSERT INTO minors (course_num,subject,minor_name) VALUES ('201','ITAL','ITALIAN');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('250','ITAL','ITALIAN');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('281','ITAL','ITALIAN');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('282','ITAL','ITALIAN');

-- JEWISH STUDIES
INSERT INTO minors (course_num,subject,minor_name) VALUES ('201','REST','JEWISH STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('204','REST','JEWISH STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('208','REST','JEWISH STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('272','HIST','JEWISH STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('349','HIST','JEWISH STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('370','ENG','JEWISH STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('371','ENG','JEWISH STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('373','ENG','JEWISH STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('303','POSC','JEWISH STUDIES');

-- AMERICAN/CARIBBEAN STUDIES
INSERT INTO minors (course_num,subject,minor_name) VALUES ('273','HIST','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('274','HIST','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('350','POSC','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('260','SPAN','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('154','SPAN','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('270','SPAN','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('233','ANTH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('255','ART','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('202','BUS','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('430','BUS','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('442','BUS','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('325','COM','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('488','COM','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('442','ECON','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('302','HONR','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('442','MDIA','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('152','SPAN','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('153','SPAN','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('154','SPAN','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('220','SPAN','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('260','SPAN','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('315','SPAN','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('335','SPAN','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('270','SPAN','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('370','SPAN','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('392','SPAN','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('394','SPAN','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('415','SPAN','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('430','SPAN','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('433','SPAN','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('477','SPAN','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('480','SPAN','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('315','FREN','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('273','HIST','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('274','HIST','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('375','HIST','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('213','POSC','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('113','POSC','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('236','POSC','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('350','POSC','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('219','REST','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('225','REST','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('395','SOCW','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('103','PHIL','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('105','INTD','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('209','INTD','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('212','INTD','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('213','INTD','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('477','INTD','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('241','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('210','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('310','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('330','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('410','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('420','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('477','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('321','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('331','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('393','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('394','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('411','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('412','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('421','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('422','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('423','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('424','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('430','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('440','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('441','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('450','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('451','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('452','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('120','CMPT','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','FYS','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('120','ENG','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','PHIL','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('241','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('242','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('120','CMPT','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','PHIL','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','FYS','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('120','ENG','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('343','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('310','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('210','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('300','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('300','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('300','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('300','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('300','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('477','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('300','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('241','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('310','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('210','MATH','AMERICAN/CARIBBEAN STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('205','MATH','AMERICAN/CARIBBEAN STUDIES');

-- MEDIEVAL AND RENAISSANCE STUDIES
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','ARAB','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('102','ARAB','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('105','FREN','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('106','FREN','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('105','ITAL','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('106','ITAL','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','LAT','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('102','LAT','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('105','SPAN','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('106','SPAN','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('245','ART','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('380','ART','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('212','ENG','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('221','ENG','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('270','ENG','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('301','ENG','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('320','ENG','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('324','ENG','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('325','ENG','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('329','ENG','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('330','ENG','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('331','ENG','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('361','ENG','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('248','HIST','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('249','HIST','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('341','HIST','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('342','HIST','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('250','ITAL','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('150','SPAN','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('420','SPAN','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('424','SPAN','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('425','SPAN','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('340','MUS','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('344','MUS','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('321','PHIL','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('311','PHIL','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('203','REST','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('204','REST','MEDIEVAL AND RENAISSANCE STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('243','REST','MEDIEVAL AND RENAISSANCE STUDIES');

-- MUSIC
INSERT INTO minors (course_num,subject,minor_name) VALUES ('112','MUS','MUSIC');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('113','MUS','MUSIC');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('212','MUS','MUSIC');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('213','MUS','MUSIC');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('351','MUS','MUSIC');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('251','MUS','MUSIC');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('250','MUS','MUSIC');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('252','MUS','MUSIC');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('253','MUS','MUSIC');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('254','MUS','MUSIC');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('255','MUS','MUSIC');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('256','MUS','MUSIC');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('103','MUS','MUSIC');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('120','MUS','MUSIC');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('220','MUS','MUSIC');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('105','MUS','MUSIC');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('106','MUS','MUSIC');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('226','MUS','MUSIC');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('242','MUS','MUSIC');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('247','MUS','MUSIC');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('248','MUS','MUSIC');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('330','MUS','MUSIC');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('335','MUS','MUSIC');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('340','MUS','MUSIC');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('344','MUS','MUSIC');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('341','MUS','MUSIC');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('342','MUS','MUSIC');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('343','MUS','MUSIC');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('346','MUS','MUSIC');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('378','MUS','MUSIC');

-- PHILOSOPHY
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','PHIL','PHILOSOPHY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('200','PHIL','PHILOSOPHY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('240','PHIL','PHILOSOPHY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('210','PHIL','PHILOSOPHY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('321','PHIL','PHILOSOPHY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('211','PHIL','PHILOSOPHY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('323','PHIL','PHILOSOPHY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('324','PHIL','PHILOSOPHY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('325','PHIL','PHILOSOPHY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('213','PHIL','PHILOSOPHY');

-- POLITICAL SCIENCE
INSERT INTO minors (course_num,subject,minor_name) VALUES ('112','POSC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('111','POSC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('113','POSC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('110','POSC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('218','POSC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('232','POSC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('233','POSC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('213','POSC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('236','POSC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('251','POSC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('252','POSC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('271','POSC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('280','POSC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('290','POSC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('325','POSC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('202','POSC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('210','POSC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('211','POSC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('212','POSC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('214','POSC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('240','POSC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('289','POSC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','FYS','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','PHIL','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('120','ENG','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('111','POSC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('110','POSC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('112','POSC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('113','POSC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('103','CMPT','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('200','POSC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('200','POSC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('200','POSC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('235','POSC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('300','POSC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('300','POSC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('477','POSC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','PSYC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('350','PSYC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('351','PSYC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('478','PSYC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('103','CMPT','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('130','MATH','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','FYS','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('120','ENG','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','PHIL','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','PSYC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('130','MATH','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','PHIL','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('103','CMPT','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','FYS','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('120','ENG','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('350','PSYC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('351','PSYC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('301','PSYC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('487','PSYC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('487','PSYC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('478','PSYC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','FYS','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('130','MATH','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','PHIL','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('103','CMPT','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('120','ENG','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','PSYC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('105','CRJU','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','CRJU','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('110','POSC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('350','PSYC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('351','PSYC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('201','CRJU','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('221','CRJU','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('230','CRJU','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('235','CRJU','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('250','CRJU','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('304','CRJU','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('301','CRJU','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('303','CRJU','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('305','CRJU','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('370','CRJU','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('301','PSYC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('487','PSYC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('477','CRJU','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('488','PSYC','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('496','CRJU','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('497','CRJU','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('440','CRJU','POLITICAL SCIENCE');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','PSYC','POLITICAL SCIENCE');

-- RELIGIOUS STUDIES
INSERT INTO minors (course_num,subject,minor_name) VALUES ('201','REST','RELIGIOUS STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('207','REST','RELIGIOUS STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('208','REST','RELIGIOUS STUDIES');

-- SOCIOLOGY
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','SOC','SOCIOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('336','SOC','SOCIOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('341','SOC','SOCIOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('440','SOC','SOCIOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('450','SOC','SOCIOLOGY');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('480','SOC','SOCIOLOGY');

-- SOCIAL WORK
INSERT INTO minors (course_num,subject,minor_name) VALUES ('101','SOC','SOCIAL WORK');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('230','SOCW','SOCIAL WORK');

-- SPANISH LANGUAGE STUDIES

-- WOMEN’S STUDIES
INSERT INTO minors (course_num,subject,minor_name) VALUES ('130','WMST','WOMEN’S STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('232','BIOL','WOMEN’S STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('350','COM','WOMEN’S STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('400','COM','WOMEN’S STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('200','ECON','WOMEN’S STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('220','ENG','WOMEN’S STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('232','HIST','WOMEN’S STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('267','HIST','WOMEN’S STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('314','HIST','WOMEN’S STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('325','HIST','WOMEN’S STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('332','HIST','WOMEN’S STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('385','WMST','WOMEN’S STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('314','POSC','WOMEN’S STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('320','POSC','WOMEN’S STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('206','PSY','WOMEN’S STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('331','PSY','WOMEN’S STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('336','SOC','WOMEN’S STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('341','SOC','WOMEN’S STUDIES');
INSERT INTO minors (course_num,subject,minor_name) VALUES ('370','SPAN','WOMEN’S STUDIES');

