-- Generated by http://typexpert.net online CSV to SQL converter

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ACC','213','ACCOUNTING SYSTEMS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ACC','221L','INTERM ACCTG I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ACC','221','INTERM ACCTING I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ACC','221','INTERM ACCTING I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ACC','221','INTERM ACCTING I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ACC','221','INTERM ACCTING I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ACC','201','MANAGERIAL ACCTNG');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ACC','204','MANAGERIAL ACCTNG');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ACC','104','FINANCIAL ACCTNG');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ACC','194','FINANCIAL ACCTNG');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ACC','103','3D DESIGN');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ANT','102','ANTHROPOLOGY II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ART','102','ART 20TH CENT');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ART','254','PHOTOJOURNALISM');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ART','145','DIGTL LAYOUT+DESIGN');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ART','123','ADV DRAWING I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ART','151','INTERM PHOTOGRAPH');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ART','140','GRAPHIC DESIGN I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ART','130','BASIC PRINTMAKING');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ART','226','BASIC PRINTMAKING');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ART','230','BASIC PRINTMAKING');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ART','113','INTERM DRAWING');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ART','121','INTERM PAINTING');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ART','204','INTERM PAINTING');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ART','111','FUND ART DES II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ART','101','HIST WEST ART I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ART','105','BASIC PHOTO');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ART','150','BASIC PHOTO');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ART','104','BASIC PAINTING');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ART','104','FUND OF ART');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ART','104','BASIC PAINTING');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ART','120','BASIC PAINTING');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ART','104','FUND OF ART');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ART','112','BASIC DRAWING');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ART','107','BASIC SCULPTURE');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ART','110','FUND ART-DESIGN');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('AST','131','INTRO COSMOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('AST','131','INTRO COSMOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('AST','131','INTRO COSMOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('AST','131','INTRO COSMOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BH','205','MARRIAGE & FAMILY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BH','103','SOCIAL PROBLEMS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BH','207','FOUNDATIONS OF EDUCATION');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BHS','104','SOCIAL INEQUALITY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BHS','209','SOCIOLOGY MINORIT');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BHS','205','MARRIAGE & FAMILY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BHS','242','DRUG/ALCOHOL ABUS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BHS','110','INTRO TO SOC WORK');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BHS','262','JUVENILE DELINQ');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BHS','142','CRIMINOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BHS','142','CRIMINOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BHS','142','Criminology');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BHS','142','Criminology');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BHS','102','SOCIAL PROBLEMS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BHS','103','SOCIAL PROBLEMS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BHS','103','SOCIAL PROBLEMS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BHS','103L','SOCIAL PROBLEMS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BHS','214','ARCHAEOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BHS','917','ARCHAEOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BHS','206','CULTURAL ANTHROPOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BHS','103','SOCIAL PROBLEMS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BHS','103','SOCIAL PROBLEMS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BHS','202','PHYSICAL ANTHROPOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BHS','207','PHIL OF EDUCATION');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BHS','101','INTRO SOCIOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BHS','203','INTRO SOCIOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BHS','230','INTRO SOCIOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','203','INVERT ZOOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','107','Ecology');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','107','ECOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','107','INTRO HUMAN BIOL');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','107','Ecology');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','107','ECOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','107','INTRO HUMAN BIOL');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','205','GENETICS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','920','ENVIRN MICROBIO');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','207','MICROBIOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','212','MICROBIOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','107','Ecology');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','107','ECOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','103','HUMAN BIOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','103','HUMAN BIOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','103','HUMAN BIOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','103','HUMAN BIOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','107','INTRO HUMAN BIOL');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','204','BOTANY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','915','CELLULAR BIOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','210','HUM ANTMY&PHYS II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','210','MAMMALIAN PHYSIOL');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','210','HUM ANTMY&PHYS II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','132','HUM ANTMY&PHYSII');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','210','MAMMALIAN PHYSIOL');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','110','HUMAN ANTMY & PHYS II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','131','HUM ANTMY&PHYS I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','209','HUM ANTMY&PHYS I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','209','MAMMALIAN ANAT');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','109','HUMAN ANTMY & PHYS I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','122','HUMAN NUTRITION');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','102','GEN BIOLOGY II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','106','GEN BIOLOGY II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','105','GEN BIOLOGY I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','101','GENERAL BIOLOGY I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','102L','GEN BIOL LAB II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','102LAB','GEN BIOL LAB II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','1019L','GEN BIO LAB I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','101L','GEN BIOLOGY LAB I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','101LAB','GEN BIOLOGY LAB I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','1019','GEN BIO I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIO','221','INTRO ENVIRON ISS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIOL','102L','GEN BIOL LAB II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIOL','101L','GEN BIOLOGY LAB I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BIOL','102','GEN BIOLOGY II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BOM','101','COMM PRINCIPLES');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BRJ','206','CRIM & SCI INVEST');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BS','103','SOCIAL PROBLEMS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BUS','215','BUSINESS LAW I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BUS','215','BUSINESS LAW I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BUS','382N','LGL FOUND OF BUS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BUS','216','BUSINESS LAW II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BUS','216','BUSINESS LAW II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BUS','125','BUSINESS LAW I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BUS','215','BUSINESS LAW I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BUS','215','BUSINESS LAW I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BUS','233','BUSINESS LAW I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BUS','241','BUSINESS LAW I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BUS','208','SMALL BUS MANAGMNT');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BUS','107','MARKET MANAGEMENT');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BUS','131','REAL PROP & TITLE');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BUS','244','HR MANAGEMENT');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BUS','122','MANAGERIAL ACCTNG');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BUS','110','ACCESS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BUS','109','EXCEL');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BUS','112','WORDPROCESSING');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BUS','115','THEORY OF MUSIC I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BUS','105','PRINC ADVERTISING');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BUS','100N','INTRO BUS & MGT');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BUS','100N','INTRO BUS & MGT');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BUS','104','INTRO BUS & MGT');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BUS','162','INTRO FASH INDUST');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('BYS','207','PHIL OF EDUCATION');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CHE','232L','ORG CHEM LAB');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CHE','232','ORG CHEMISTRY II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CHE','231','ORGANIC CHEM I+LAB');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CHE','231LAB','ORG CHEM LAB');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CHE','232','ORG CHEMISTRY II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CHE','231','ORGANIC CHEM I+LAB');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CHE','116','INTR ORGAN CHEM');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CHE','122','GENERAL CHEM. II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CHE','121','GEN CHEMISTRY I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CHE','122L','GEN CHEM LAB II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CHE','122LAB','GEN CHEM LAB II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CHE','121L','GEN CHEM LAB I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CHE','121LAB','GEN CHEM LAB I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CHE','273','GENERAL CHEM. II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CHE','101','INTRO CHEMISTRY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CHE','111','INTRO CHEMISTRY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CHEM','2263','ORG CHEM LAB');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CHEM','116','SELF,NATURE-HIST');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CHEM','2262','ORG CHEM II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CHEM','2261','ORG CHEM I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CHEM','231','ORGANIC CHEM I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CHEM','121','GEN CHEMISTRY I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CHEM','122','GENERAL CHEM. II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CHEM','122L','GEN CHEM LAB II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CHEM','111','INTRO CHEMISTRY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CHM','101','INTRO TO SOC WORK');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CHS','242','DRUG/ALCOHOL ABUSE');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CIS','212','SYS ANALYSIS METH');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CIS','212','SYSTEMS ANALYSIS & DESIGN');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CIS','212','SYS ANALYSIS METH');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CIS','212','SYSTEMS ANALYSIS & DESIGN');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CIS','117','DATA COMMUNICATIONS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CIS','227','ARCH HARDWARE+SFTWR');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CIS','126','UNIX');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CIS','126','UNIX/LINEX');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CIS','126','UNIX');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CIS','126','UNIX/LINEX');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CIS','214L','OBJ ORNT PRG C++');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CIS','214','OBJ-ORNT PRG C++');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CIS','113','VISUAL BASIC PROG');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CIS','215','COMP SCI I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CIS','215','Internet Prog Java');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CIS','111','COMP STUD CONC');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CIS','2130L','COMP STUD CONC');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CIS','111','COMPUTER SYSTEMS & APPLICATION');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CIS','111','INFO TECH&SYS CONCEPTS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CIS','111','TECHNOLOGY FOR 21st CENTURY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CIS','111','COMP STUD CONC');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CIS','111','COMPUTER SYSTEMS & APPLICATION');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CIS','111','INFO TECH&SYS CONCEPTS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CIS','111','TECHNOLOGY FOR 21st CENTURY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CIS','215','COMP SCI I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CIS','215','Internet Prog Java');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CIS','111','COMP STUD CONC');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CIS','111','COMPUTER SYSTEMS & APPLICATION');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CIS','111','INFO TECH&SYS CONCEPTS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CIS','111','TECHNOLOGY FOR 21st CENTURY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CIS','108','INFO+COMP LITERACY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CIS','213','INFO+COMP LITERACY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CLP','101','EMPLOYMENT PRACT');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CLP','101','EMPLOYMENT PRACT');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CLP','101','EMPLOYMENT PRACT');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CLP','101','EMPLOYMENT PRACT');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CLS','213','COMP STUD CONC');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CMH','201','SOC SERV THEO/PRA');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CMH','101','INTRO TO SOC WORK');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CMSC','412L','ROBOTICS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CMSC','121L','COMPUTER SCI II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CMSC','120L','COMPUTER SCI I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CO','140','Media and Society');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('COM','220','MEDIA PERFORM TECH');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('COM','250','ADV TV PRODUCTION');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('COM','262','ADV TV PRODUCTION');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('COM','233','AUDIO FOR MEDIA');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('COM','244','SCREENWRITING');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('COM','245','SCREENWRITING');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('COM','908','SCREENWRITING');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('COM','244','SCREENWRITING');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('COM','120','INTRO MEDIA WRITING');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('COM','120','WRIT FOR MEDIA');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('COM','110','TV PRODUCTION');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('COM','249','TV PRODUCTION');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('COM','110','VIDEO PRODUCTION');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('COM','207','ART OF FILM');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('COM','240','BROADCASTING');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('COM','110','TV PRODUCTION');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('COM','110','VIDEO PRODUCTION');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('COM','201L','COMMUNIC/SOCIETY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('COM','140','MEDIA AND SOCIETY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('COM','120','INTRO MEDIA WRITING');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('COM','120','WRIT FOR MEDIA');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('COM','101','COMM PRINCIPLES');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('COM','101','Intro Comm Media');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('COM','101','COMM PRINCIPLES');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('COM','203','COMM PRINCIPLES');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('COM','101','Intro Comm Media');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CPS','231','COMPUTER SCI I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CPS','231','Data Structures');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CPS','141','CMSC COURSE');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CPS','141','Intro Comp Sci Prog');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CPS','231','COMPUTER SCI I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CPS','231','Data Structures');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CPS','100','COMPUTING STUD SEM');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CRJ','144','JUV JUST SYST');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CRJ','263','CRIM PROC II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CRJ','264','CRIM PROC I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CRJ','201','CRIM JUS ORG&ADM');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CRJ','265','US COURTS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CRJ','206','CRIM & SCI INVEST');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('CRJ','141','INTRO CRIM JUST');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('DAN','104','MODERN DANCE I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('DAN','101','INTRO TO DANCE');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('DAN','102','BEG CLASS BALLET');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('DTN','102','TOPICS IN NUTRITION');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ECN','105','ECON-SOCIAL ISSUES');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ECO','224','INTERNATION ECON');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ECO','218','LABOR RELATIONS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ECO','121','ENVIRON ECONOMICS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ECO','105','ECON-SOCIAL ISSUES');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ECO','115','ECON-SOCIAL ISSUES');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ECO','202','PRINC MACROECONOM');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ECO','202','PRINC MACROECONOM');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ECO','201','PRINC MICROECONOM');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ECO','201','PRINC MICROECONOM');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ECO','106','PRINC MICROECONOM');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ECO','201','PRINC MICROECONOM');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ECO','201','PRINC MICROECONOM');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ECO','208','PRINC MICROECONOM');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ECO','216','PRINC MICROECONOM');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ECO','102','PRINC MACROECONOM');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ECO','202','PRINC MACROECONOM');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ECO','202','PRINC MACROECONOM');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ECO','215','PRINC MACROECONOM');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ECON','102L','PRINC MICROECONOM');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ECON','201','PRINC MICROECONOM');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ECOO','12','PRINC MICROECONOM');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ECOO','11','PRINC MACROECONOM');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ECOP','105','ECON-SOCIAL ISSUES');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('EN','12','COLLEGE WRITING I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ENG','209','WORKSHOP FICTION');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ENG','309','WORKSHOP FICTION');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ENG','208','MODERN DRAMA');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ENG','224','ENG COURSE/LIT');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ENG','224L','ETHNIC AMER LIT');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ENG','214','CONT ENG-AM POET');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ENG','215','CONT ENG-AM POET');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ENG','227','FILM & LITERATURE');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ENG','230','SHAKESPEARE');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ENG','207','RISE DEL ENG DRAM');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ENG','217','TECH-PROF WRITE');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ENG','210','POETRY WORKSH');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ENG','212','Greek/Roman Lit Translation');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ENG','216','AM SHORT FIC');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ENG','230','SHAKESPEARE');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ENG','218','ADVANCED WRITING');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ENG','202','ENGLISH LIT II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ENG','201','ENGLISH LIT I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ENG','204','AMERICAN LIT II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ENG','203','AMERICAN LIT I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ENG','102','COLL WRITING II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ENG','102','WRITING FOR COLLEGE');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ENG','180','COLL WRITING II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ENG','102','COLL WRITING II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ENG','103','COLL WRITING II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ENG','102','WRITING FOR COLLEGE');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ENG','101','COLLEG WRITNG I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ENG','111','COLLEG WRITNG I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ENT','1051','FINANCIAL ACCTNG');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('FIN','2011','FINANCIAL MGMT');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('FIN','203','FINANCIAL MGMT');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('FRE','302','ADV READ-CONV II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('FRE','301','ADV READ-CONV I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('FRE','205','LANG & CULT II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('FRE','204','LANG & CULT I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('FRE','202','INTERM FREN II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('FRE','201','INTERM FREN I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('FRE','102','ELEM FREN II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('FRE','101','ELEM FREN I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('GERM','301','GERM LANG/CULT I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('GERM','202','INTERM GERMAN II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('GERM','201','INTERM GERMAN I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('GERM','N201','INTERM GERMAN I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('GERM','102','ELEM GERMAN II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('GERM','101','ELEM GERMAN I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('GOV','219','INTERNAT POLITICS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('GOV','221','COMP POL EST EURO');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('GOV','201','POLIT THOUGHT III');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('GOV','122','AM STATE/URBAN PO');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('GOV','121','AMER NATL GOVT');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('GOV','151','INTRO TO LAW');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('GOVT','121','AMER NATL GOVT');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('HED','134','FIRST AID/CPR');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('HED','123L','CONTEMP HEALTH');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('HIS','206','HIST LATIN AM II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('HIS','914','MODERN CHINA');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('HIS','217','TRADITIONAL CHINA');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('HIS','207','RUSSIA TO 1850');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('HIS','221','Medieval Europe 600-1500');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('HIS','209','BLACK AMER EXP');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('HIS','214','AMERICAN FEMINISM');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('HIS','104','AMER HIST II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('HIS','114','AMER HIST II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('HIS','273','AMER HIST II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('HIS','103','AMER HIST I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('HIS','121','AMER NATNL GOVT');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('HIS','102','THEMES IN MOD HIST');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('HIS','108','THEMES IN MOD HIST');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('HIST','104','AMER HIST II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('HIST','108','THEMES IN MOD HIST');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('HLTH','202N','FIRST AID/CPR');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('HMS','263','CRIM PROCEDR II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('HMS','264','CRIM PROCEDURE I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('HMS','242','DRUG/ALCOHOL ABUS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('HMS','262','JUVENILE DELINQ');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('HMS','141','INTRO CRIM JUST');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('IS','310','ARCH-HARD-SOFTWARE');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ITA','202','Interm Italian II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ITA','201','Interm. Italian  I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ITA','101','ELEM ITAL I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ITL','205','ADV ITALIAN II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ITL','204','ADV ITALIAN I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ITL','202','INTERM ITALIAN II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ITL','201','INTERM ITAL I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ITL','102','ELEM ITALIAN II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('ITL','101','ELEM ITAL I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('LAW','212','BUSINESS LAW II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('LITL','102','ELEM ITALIAN II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MA','102','INTRO-STATS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MAR','200','MARKET MANAGEMENT');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MAT','223','CALCULUS III');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MAT','224','DIFFERENT EQUAT');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MAT','217','INT MATH REASON');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MAT','140','DISCRETE MATH I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MAT','214','DISCRETE MATH I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MAT','222','CALCULUS II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MAT','107','MATH COURSE');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MAT','107','MATH COURSE');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MAT','221','CALC:MGMT APPLCTN');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MAT','221','CALCULUS I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MAT','215','LINEAR ALGERBRA');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MAT','118','INTRO-STATISTICS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MAT','115','PRE-CALCULUS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MAT','185','Precalculus');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MAT','185','Precalculus');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MAT','185','PRECALCULUS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MAT','185','PRECALCULUS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MAT','125','CALC:MGMT APPLCTN');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MAT','221','CALC:MGMT APPLCTN');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MAT','221','CALCULUS I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MAT','101','EXCURS-CLASSICAL');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MAT','109L','EXCURS-CLASSICAL');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MAT','109','EXCURSIONS IN MATH I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MAT','110','INTERM ALGEBRA');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MAT','184','INTERM ALGEBRA');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MATH','122','CALCULUS II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MATH','222','CALCULUS II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MATH','121','CALCULUS I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MATH','118','INTRO-STATISTICS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MATH','130','INTRO-STATISTICS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MATH','125L','CALC:MGMT APPLCTN');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MATH','110','INTERM ALEGBRA');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MGT','205','MANAG ORG BEHAV');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MLT','202','PARASITOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MUS','241','ADV CLASS PIANO');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MUS','211','IND VOCAL STUDY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MUS','221','CHORAL SING III');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MUS','136','ORCHESTRA');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MUS','137','ORCHESTRA');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MUS','117','BRASS WIND ENSEMB');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MUS','116','THRY OF MUSIC II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MUS','210','VOICE STUDY II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MUS','104','INTRO MUSIC THEORY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MUS','115','THEORY OF MUSIC I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MUS','122','CHORAL SINGING II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MUS','121','CHORAL SINGING I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MUS','142','PIANO II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MUS','141','BG CLSS PIANO I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('MUS','135','JAZZ AND SOUND');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('OFT','232','EXCEL');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('OFT','108','WORD PROCESSING');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('OFT','231','WORDPROCESSING');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PAL','290','CRJU INTERN I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PAL','240','CIV LITIG, PRACT');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PAL','220','WILLS TRUSTS ESTA');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PAL','230','BUSINESS LAW I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PAL','210','FAMILY LAW');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PAL','120','INTR LEG WRIT-RES');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PAR','230','Clinical III');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PAR','220','Clinical II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PAR','120','Clinical I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PAR','206','Patient Assessment');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PAR','201','Trauma');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PE','123','HANDBALL/RACQUETB');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PED','116','HATHA YOGA');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PED','116','HATHA YOGA');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PED','116','Yoga');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PED','116','Yoga');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PED','180','BEG SWIM/NONSWIM');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PED','170','SKIING');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PED','123','HANDBALL/RACQUETB');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PED','132','SOCCER');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PED','144','MODERN DANCE I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PED','124','TENNIS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PED','103','CONDITIONING');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PED','109','ARCHERY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PED','131','GOLF');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PED','141','INTRO TO DANCE');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PHI','205','Ethical Theory');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PHI','205','ETHICS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PHI','203','WORLD RELIGIONS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PHI','107','INTRO TO LOGIC');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PHI','207','INTRO TO LOGIC');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PHI','205','Ethical Theory');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PHI','205','ETHICS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PHI','204','WORLD VIEW VALUES');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PHI','201','PHILOSOPHY COURSE');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PHI','201','PHILOSOPHY: PRIMARY ISSUES');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PHIL','203','WORLD RELIGIONS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PHS','111','WEATHER AND CLIMATE');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PHS','111','WEATHER AND CLIMATE');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PHS','111','WEATHER AND CLIMATE');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PHS','111','WEATHER AND CLIMATE');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PHS','203','WORLD RELIGIONS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PHS','114','INTRO CHEMISTRY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PHS','103','INTRO ENVIRON ISS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PHY','251','GEN PHYSICS III');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PHY','122411','GEN PHYS LAB II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PHY','122L','GEN PHYSIC LAB II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PHY','122','GEN PHYSICS II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PHY','152L','GEN PHYSICS LAB II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PHY','121','GEN PHYSICS I+LAB');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PHY','151L','GEN PHYSICS LAB I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PHY','121L','PHYSICS ELECTIVE');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PHY','122','GEN PHYSICS II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PHY','122410','GEN PHYSICS II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PHY','152','GEN PHYSICS II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PHY','121','GEN PHYSICS I+LAB');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PHY','151','GENERAL PHYSICS I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PHY','107','INTRO TO LOGIC');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PHYS','121','GEN PHYSICS I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PLS','201','CRIM JUS ORG&ADM');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PLS','205','CRIM & SCI INVEST');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('POS','219','INTERNAT POLITICS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('POS','122','AM STATE/URBAN PO');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('POS','121','AMER NATL GOVT');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PSY','203','CHILD DEVELOPMENT');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PSY','236','HUM BEH-SOC ENV');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PSY','102','PSYCHOLOGY COURSE');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PSY','102','SOCIAL WORK ELECTIVE');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PSY','222','ADOL, ADULT-AGIN');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PSY','204','PSYC OF THE ADOLSCT');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PSY','203','CHILD DEVELOPMENT');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PSY','221','CHILD DEVELOPMENT');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PSY','209','INTRO:PHYSIO PSYC');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PSY','205','SOCIAL PSYCHOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PSY','206','SOCIAL PSYCHOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PSY','114','PSY OF INTERP COM');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PSY','124','PSY OF INTERP COM');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PSY','134','PSY OF INTERP COM');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PSY','901','PSYCH OF RETARDTN');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PSY','211','EDUC PSYCHOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PSY','235','THE EXCEPT CHILD');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PSY','210','PSYC, BIO SEX DIF');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PSY','201','ABNORMAL PSYCHOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PSY','101','INTRO PSYCHOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PSY','111','INTRO PSYCHOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PSY','111L','INTRO PSYCHOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PSYC','134','PSY OF INTERP COM');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PSYC','101','INTRO PSYCHOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('PSYC','111','INTRO PSYCHOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('REA','100','COLLEGE READING');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('REA','103','COLLEGE READING');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('REA','105','COLLEGE READING');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('RET','211','FASH EMPLOY SEM');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('RET','101','MARKET MANAGEMENT');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('RET','204','VISUAL MERCH');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('RET','106','PRINC RETAILING');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('SCS','264','CRIM PROCEDR II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('SCS','263','CRIM PROCEDURE I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('SCS','242','DRUG/ALCOHOL ABUS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('SCS','262','JUVENILE DELINQ');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('SCS','134','PSYCHOLOGY COURSE');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('SCS','142','CRIMINOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('SCS','141','INTRO CRIM JUST');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('SO','207','CRIMINOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('SOC','202','SOCIAL INEQUALITY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('SOC','202','SOCIAL INEQUALITY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('SOC','101','INTRO SOCIOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('SOC','113','INTRO SOCIOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('SOC','203','INTRO SOCIOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('SOCI','101','INTRO SOCIOLOGY');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('SPA','320','SPAN-HISPANICS I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('SPA','302','ADV SPAN II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('SPA','301','ADV SPANISH I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('SPA','2040','INTER SPAN II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('SPA','202','INTER SPANISH II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('SPA','2030','INTER SPAN I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('SPA','201','INTER SPANISH I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('SPA','102','ELEM SPANISH II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('SPA','101','ELEM SPANISH I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('SPAN','199','ELEM SPANISH II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('SPC','101','PUBLIC PRESENTAT.');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('SPE','219','INTERCULT COMM');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('SPE','201','AUGUMENT & DEBATE');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('SPE','10','PUBLIC PRESENTAT.');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('SPE','100','PUBLIC PRESENTAT.');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('SPE','101','PUBLIC PRESENTAT.');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('SPE','101L','PUBLIC PRESENTAT.');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('SPE','903','PUBLIC PRESENTAT.');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('TEL','212','INTERNETWORKING I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('TEL','211','DATA COMMUNICATIONS');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('THE','261','THEATRE WORKSHOP');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('THE','209','ACTING II');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('THE','161','THEATRE PRACTICUM');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('THE','109','ACTING I');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('THE','105','INTRO DRAMA/PERFORM');

INSERT INTO dcc (subject, course_num, course_title) VALUES ('VIS','110','FUND ART-DESIGN');
