-- Generated by http://typexpert.net online CSV to SQL converter

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ACC','213','197520','ACCT','350');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ACC','221L','197520','ACCT','301');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ACC','221','199520','ACCT','301');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ACC','221','199520','ACCT','301');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ACC','221','197520','ACCT','301');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ACC','221','197520','ACCT','301');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ACC','201','197520','ACCT','204');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ACC','204','197520','ACCT','204');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ACC','104','197520','ACCT','203');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ACC','194','197520','ACCT','203');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ACC','103','197520','ART','201');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ANT','102','197520','ANTH','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','102','197520','ART','366');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','254','197520','ART','345');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','145','200240','ART','324');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','123','197520','ART','310');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','151','197520','ART','240');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','140','199120','ART','215');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','130','199310','ART','207');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','226','197520','ART','207');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','230','199310','ART','207');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','113','197520','ART','203');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','121','197520','ART','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','204','197520','ART','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','111','197520','ART','201');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','101','197520','ART','160');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','105','197520','ART','145');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','150','197520','ART','145');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','104','201220','ART','125');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','104','201220','ART','125');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','104','197520','ART','111');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','120','197520','ART','111');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','104','197520','ART','111');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','112','197520','ART','110');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','107','197520','ART','105');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','110','197520','ART','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('AST','131','197520','PHYS','108');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('AST','131','197520','PHYS','108');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('AST','131','199020','PHYS','108');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('AST','131','199020','PHYS','108');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BH','205','197520','REST','335');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BH','103','199540','SOC','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BH','207','200040','EDUC','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','104','199140','SOC','336');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','209','199140','SOC','336');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','205','197520','REST','335');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','242','197520','CRJU','242');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','110','197520','SOCW','230');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','262','197520','CRJU','223');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','142','199130','CRJU','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','142','201520','CRJU','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','142','199130','CRJU','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','142','201520','CRJU','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','102','199540','SOC','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','103','199540','SOC','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','103','199540','SOC','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','103L','199540','SOC','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','214','197520','ANTH','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','917','197520','ANTH','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','206','197520','ANTH','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','103','197520','SOC','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','103','197520','SOC','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','202','197520','ANTH','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','207','200040','EDUC','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','101','197520','SOC','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','203','197520','SOC','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','230','197520','SOC','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','203','197520','BIOL','420');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','107','201140','ENSC','360');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','107','201140','ENSC','360');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','107','201140','ENSC','360');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','107','197520','BIOL','330');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','107','197520','BIOL','330');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','107','197520','BIOL','330');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','205','197520','BIOL','320');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','920','198940','ENSC','313');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','207','197520','BIOL','312');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','212','197520','BIOL','312');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','107','201320','BIOL','237');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','107','201320','BIOL','237');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','103','201340','BIOL','237');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','103','197520','BIOL','237');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','103','201340','BIOL','237');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','103','197520','BIOL','237');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','107','201320','BIOL','237');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','204','197520','BIOL','211');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','915','197520','BIOL','210');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','210','199020','BIOL','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','210','199020','BIOL','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','210','197520','BIOL','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','132','200040','BIOL','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','210','197520','BIOL','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','110','200040','BIOL','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','131','200040','BIOL','201');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','209','199020','BIOL','201');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','209','199020','BIOL','201');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','109','200040','BIOL','201');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','122','197520','HLTH','201');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','102','200540','BIOL','131');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','106','200640','BIOL','131');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','105','200640','BIOL','130');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','101','200640','BIOL','130');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','102L','197520','BIOL','113');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','102LAB','197520','BIOL','113');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','1019L','197520','BIOL','112');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','101L','197520','BIOL','112');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','101LAB','197520','BIOL','112');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','1019','197520','BIOL','110');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','221','197520','ENSC','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIOL','102L','197520','BIOL','113');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIOL','101L','197520','BIOL','112');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIOL','102','197520','BIOL','111');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BOM','101','199740','COM','100');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BRJ','206','197520','CRJU','206');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BS','103','199540','SOC','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','215','197520','BUS','382');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','215','197520','BUS','382');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','382N','200140','BUS','382');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','216','197520','BUS','381');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','216','197520','BUS','381');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','125','197520','BUS','380');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','215','197520','BUS','380');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','215','197520','BUS','380');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','233','197520','BUS','380');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','241','197520','BUS','380');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','208','199640','FASH','361');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','107','197520','BUS','340');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','131','199240','PRLG','313');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','244','197520','BUS','301');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','122','197520','ACCT','204');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','110','199640','CMPT','154');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','109','199640','CMPT','152');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','112','199640','CMPT','151');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','115','197520','MUS','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','105','199720','COM','110');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','100N','200140','BUS','100');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','100N','200140','BUS','100');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','104','200140','BUS','100');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','162','199640','FASH','100');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BYS','207','197520','PHIL','233');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHE','232L','200640','CHEM','216');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHE','232','197520','CHEM','216');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHE','231','197520','CHEM','215');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHE','231LAB','197520','CHEM','213');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHE','232','197520','CHEM','212');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHE','231','197520','CHEM','211');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHE','116','199120','CHEM','201');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHE','122','200340','CHEM','132');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHE','121','200340','CHEM','131');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHE','122L','197520','CHEM','114');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHE','122LAB','197520','CHEM','114');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHE','121L','197520','CHEM','113');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHE','121LAB','197520','CHEM','113');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHE','273','197520','CHEM','112');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHE','101','197520','CHEM','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHE','111','197520','CHEM','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHEM','2263','197520','CHEM','213');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHEM','116','199140','INTD','213');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHEM','2262','197520','CHEM','212');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHEM','2261','197520','CHEM','211');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHEM','231','197520','CHEM','211');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHEM','121','200340','CHEM','131');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHEM','122','200340','CHEM','131');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHEM','122L','197520','CHEM','114');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHEM','111','197520','CHEM','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHM','101','197520','SOCW','230');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHS','242','197520','CRJU','242');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','212','201320','CMPT','430');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','212','201320','CMPT','430');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','212','200740','CMPT','430');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','212','200740','CMPT','430');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','117','200740','CMPT','406');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','227','200730','CMPT','321');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','126','199740','CMPT','312');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','126','199740','CMPT','312');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','126','200740','CMPT','312');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','126','200740','CMPT','312');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','214L','199540','CMPT','310');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','214','199540','CMPT','310');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','113','199540','CMPT','236');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','215','201320','CMPT','220');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','215','201320','CMPT','220');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','111','199540','CMPT','130');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','2130L','199540','CMPT','130');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','111','199540','CMPT','130');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','111','199540','CMPT','130');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','111','199540','CMPT','130');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','111','200740','CMPT','130');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','111','200740','CMPT','130');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','111','200740','CMPT','130');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','111','200740','CMPT','130');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','215','199540','CMPT','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','215','199540','CMPT','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','111','201340','CMPT','103');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','111','201340','CMPT','103');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','111','201340','CMPT','103');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','111','201340','CMPT','103');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','108','199540','CMPT','103');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','213','199540','CMPT','103');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CLP','101','201420','CRDV','100');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CLP','101','199240','CRDV','100');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CLP','101','201420','CRDV','100');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CLP','101','199240','CRDV','100');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CLS','213','199540','CMPT','130');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CMH','201','197520','SOCW','330');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CMH','101','197520','SOCW','230');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CMSC','412L','200420','CMPT','412');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CMSC','121L','199540','CMPT','121');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CMSC','120L','199540','CMPT','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CO','140','201220','COM','201');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','220','199740','COM','396');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','250','199740','COM','393');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','262','199740','COM','393');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','233','199740','COM','387');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','244','200120','COM','321');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','245','200120','COM','321');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','908','200120','COM','321');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','244','200120','MDIA','301');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','120','199740','COM','289');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','120','199740','COM','289');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','110','199740','COM','287');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','249','199740','COM','287');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','110','199740','COM','287');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','207','199740','COM','286');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','240','199740','COM','285');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','110','201340','MDIA','203');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','110','201340','MDIA','203');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','201L','199740','COM','201');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','140','201240','COM','201');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','120','201340','MDIA','201');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','120','201340','MDIA','201');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','101','201140','COM','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','101','201140','COM','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','101','199740','COM','100');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','203','199740','COM','100');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','101','199740','COM','100');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CPS','231','201340','CMPT','220');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CPS','231','201340','CMPT','220');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CPS','141','201340','CMPT','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CPS','141','201340','CMPT','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CPS','231','197520','CMPT','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CPS','231','197520','CMPT','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CPS','100','199540','CMPT','110');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CRJ','144','199020','CRJU','305');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CRJ','263','197520','CRJU','304');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CRJ','264','197520','CRJU','303');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CRJ','201','199540','CRJU','301');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CRJ','265','200520','CRJU','250');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CRJ','206','197520','CRJU','206');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CRJ','141','197520','CRJU','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('DAN','104','197520','PHED','128');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('DAN','101','199120','PHED','106');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('DAN','102','199040','PHED','105');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('DTN','102','200320','BIOL','225');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECN','105','199840','ECON','150');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','224','197520','ECON','442');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','218','197520','BUS','402');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','121','197520','ECON','305');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','105','199840','ECON','150');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','115','199840','ECON','150');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','202','201040','ECON','104');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','202','201040','ECON','104');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','201','201040','ECON','103');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','201','201040','ECON','103');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','106','197520','ECON','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','201','197520','ECON','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','201','197520','ECON','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','208','197520','ECON','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','216','197520','ECON','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','102','197520','ECON','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','202','197520','ECON','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','202','197520','ECON','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','215','197520','ECON','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECON','102L','197520','ECON','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECON','201','197520','ECON','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECOO','12','197520','ECON','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECOO','11','197520','ECON','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECOP','105','199840','ECON','150');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('EN','12','197520','ENG','116');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','209','197520','ENG','382');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','309','197520','ENG','382');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','208','197520','ENG','363');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','224','199920','ENG','353');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','224L','199920','ENG','353');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','214','197520','ENG','342');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','215','197520','ENG','342');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','227','199130','ENG','339');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','230','201140','ENG','325');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','207','197520','ENG','320');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','217','197520','ENG','312');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','210','197520','ENG','311');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','212','201140','ENG','270');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','216','197520','ENG','240');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','230','201140','ENG','221');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','218','197520','ENG','218');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','202','197520','ENG','213');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','201','197520','ENG','212');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','204','197520','ENG','211');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','203','197520','ENG','210');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','102','201340','ENG','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','102','201340','ENG','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','180','197520','ENG','117');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','102','197520','ENG','117');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','103','197520','ENG','117');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','102','197520','ENG','117');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','101','197520','ENG','116');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','111','197520','ENG','116');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENT','1051','197520','ACCT','203');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('FIN','2011','197520','BUS','320');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('FIN','203','197520','BUS','320');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('FRE','302','197520','FREN','313');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('FRE','301','197520','FREN','312');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('FRE','205','197520','FREN','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('FRE','204','197520','FREN','201');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('FRE','202','197520','FREN','106');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('FRE','201','197520','FREN','105');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('FRE','102','197520','FREN','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('FRE','101','197520','FREN','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('GERM','301','197520','GERM','201');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('GERM','202','197520','GERM','106');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('GERM','201','197520','GERM','105');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('GERM','N201','197520','GERM','105');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('GERM','102','197520','GERM','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('GERM','101','197520','GERM','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('GOV','219','197520','POSC','273');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('GOV','221','197520','POSC','252');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('GOV','201','197520','POSC','243');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('GOV','122','197520','POSC','211');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('GOV','121','197520','POSC','110');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('GOV','151','197520','PRLG','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('GOVT','121','197520','POSC','110');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HED','134','200040','HLTH','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HED','123L','197520','PHED','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HIS','206','197520','HCMPTT','274');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HIS','914','200340','HCMPTT','271');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HIS','217','197520','HCMPTT','270');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HIS','207','197520','HCMPTT','260');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HIS','221','201240','HCMPTT','248');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HIS','209','199120','HCMPTT','234');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HIS','214','199120','HCMPTT','230');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HIS','104','199120','HCMPTT','227');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HIS','114','199120','HCMPTT','227');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HIS','273','199120','HCMPTT','227');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HIS','103','199120','HCMPTT','226');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HIS','121','197520','POSC','110');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HIS','102','200340','HCMPTT','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HIS','108','200340','HCMPTT','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HIST','104','199120','HCMPTT','227');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HIST','108','200340','HCMPTT','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HLTH','202N','200040','HLTH','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HMS','263','197520','CRJU','304');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HMS','264','197520','CRJU','303');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HMS','242','197520','CRJU','242');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HMS','262','197520','CRJU','223');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HMS','141','197520','CRJU','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('IS','310','199540','CMPT','321');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ITA','202','201340','ITAL','106');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ITA','201','201340','ITAL','105');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ITA','101','197520','ITAL','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ITL','205','199310','ITAL','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ITL','204','197520','ITAL','201');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ITL','202','197520','ITAL','106');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ITL','201','197520','ITAL','105');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ITL','102','197520','ITAL','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ITL','101','197520','ITAL','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('LAW','212','197520','BUS','381');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('LITL','102','197520','ITAL','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MA','102','197520','MATH','130');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAR','200','197520','BUS','340');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','223','199740','MATH','343');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','224','197520','MATH','321');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','217','199740','MATH','310');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','140','197520','MATH','250');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','214','197520','MATH','250');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','222','199820','MATH','242');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','107','197520','EDUC','241');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','107','197520','EDUC','241');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','221','199740','MATH','241');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','221','199740','MATH','241');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','215','197520','MATH','210');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','118','197520','MATH','130');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','115','197520','MATH','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','185','201440','MATH','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','185','197520','MATH','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','185','197520','MATH','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','185','201440','MATH','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','125','197520','MATH','115');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','221','197520','MATH','115');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','221','197520','MATH','115');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','101','197520','MATH','110');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','109L','197520','MATH','110');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','109','197520','MATH','110');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','110','197520','MATH','108');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','184','197520','MATH','108');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MATH','122','199820','MATH','242');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MATH','222','197520','MATH','222');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MATH','121','197520','MATH','221');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MATH','118','197520','MATH','130');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MATH','130','197520','MATH','130');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MATH','125L','197520','MATH','115');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MATH','110','197520','MATH','108');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MGT','205','197520','BUS','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MLT','202','197520','BIOL','421');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MUS','241','199920','MUS','410');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MUS','211','197520','MUS','351');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MUS','221','197520','MUS','301');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MUS','136','199920','MUS','234');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MUS','137','199920','MUS','234');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MUS','117','197520','MUS','231');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MUS','116','197520','MUS','220');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MUS','210','197520','MUS','213');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MUS','104','201240','MUS','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MUS','115','197520','MUS','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MUS','122','197520','MUS','111');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MUS','121','197520','MUS','110');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MUS','142','199920','MUS','108');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MUS','141','199920','MUS','107');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MUS','135','197520','MUS','106');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('OFT','232','199640','CMPT','152');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('OFT','108','199640','CMPT','151');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('OFT','231','199640','CMPT','151');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PAL','290','197520','CRJU','496');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PAL','240','197520','PRLG','422');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PAL','220','197520','PRLG','420');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PAL','230','197520','PRLG','380');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PAL','210','199310','PRLG','311');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PAL','120','197520','PRLG','210');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PAR','230','201420','BIOL','497');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PAR','220','201420','BIOL','496');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PAR','120','201420','BIOL','495');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PAR','206','201420','ATHT','310');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PAR','201','201420','ATHT','205');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PE','123','197520','PHED','133');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PED','116','199340','PHED','147');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PED','116','201340','PHED','147');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PED','116','199340','PHED','147');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PED','116','201340','PHED','147');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PED','180','197520','PHED','139');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PED','170','197520','PHED','138');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PED','123','197520','PHED','133');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PED','132','197520','PHED','130');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PED','144','197520','PHED','128');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PED','124','197520','PHED','127');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PED','103','197520','PHED','124');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PED','109','197520','PHED','123');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PED','131','197520','PHED','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PED','141','199120','PHED','106');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHI','205','199340','PHIL','300');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHI','205','199340','PHIL','300');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHI','203','199120','REST','209');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHI','107','197520','PHIL','203');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHI','207','197520','PHIL','203');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHI','205','201440','PHIL','200');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHI','205','201440','PHIL','200');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHI','204','197520','PHIL','103');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHI','201','201340','PHIL','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHI','201','201340','PHIL','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHIL','203','199120','REST','209');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHS','111','201220','ENSC','211');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHS','111','199740','ENSC','211');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHS','111','199740','ENSC','211');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHS','111','201220','ENSC','211');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHS','203','199120','REST','209');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHS','114','197520','CHEM','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHS','103','197520','ENSC','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHY','251','200220','PHYS','221');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHY','122411','197520','PHYS','214');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHY','122L','197520','PHYS','214');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHY','122','197520','PHYS','214');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHY','152L','197520','PHYS','214');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHY','121','197520','PHYS','213');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHY','151L','197520','PHYS','213');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHY','121L','197520','PHYS','213');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHY','122','197520','PHYS','212');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHY','122410','197520','PHYS','212');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHY','152','197520','PHYS','212');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHY','121','197520','PHYS','211');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHY','151','197520','PHYS','211');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHY','107','197520','PHIL','203');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHYS','121','197520','PHYS','211');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PLS','201','199540','CRJU','301');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PLS','205','197520','CRJU','206');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('POS','219','197520','POSC','273');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('POS','122','197520','POSC','211');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('POS','121','197520','POSC','110');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','203','197520','SOCW','345');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','236','197520','SOCW','345');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','102','197520','SOCW','330');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','102','197520','SOCW','330');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','222','197520','PSYC','321');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','204','200220','PSYC','318');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','203','197520','PSYC','317');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','221','197520','PSYC','317');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','209','200030','PSYC','301');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','205','197520','PSYC','220');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','206','197520','PSYC','220');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','114','197520','PSYC','215');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','124','197520','PSYC','215');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','134','197520','PSYC','215');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','901','197520','PSYC','209');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','211','197520','PSYC','208');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','235','197520','PSYC','207');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','210','197520','PSYC','206');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','201','197520','PSYC','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','101','197520','PSYC','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','111','197520','PSYC','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','111L','197520','PSYC','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSYC','134','197520','PSYC','215');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSYC','101','197520','PSYC','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSYC','111','197520','PSYC','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('REA','100','197520','LERN','105');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('REA','103','197520','LERN','105');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('REA','105','197520','LERN','105');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('RET','211','199640','FASH','400');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('RET','101','197520','BUS','340');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('RET','204','199640','FASH','285');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('RET','106','199640','FASH','265');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SCS','264','197520','CRJU','304');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SCS','263','197520','CRJU','303');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SCS','242','197520','CRJU','242');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SCS','262','197520','CRJU','223');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SCS','134','197520','PSYC','215');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SCS','142','199130','CRJU','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SCS','141','197520','CRJU','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SO','207','199130','CRJU','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SOC','202','199140','SOC','336');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SOC','202','199140','SOC','336');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SOC','101','197520','SOC','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SOC','113','197520','SOC','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SOC','203','197520','SOC','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SOCI','101','197520','SOC','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPA','320','199020','SPAN','210');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPA','302','197520','SPAN','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPA','301','197520','SPAN','201');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPA','2040','197520','SPAN','106');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPA','202','197520','SPAN','106');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPA','2030','197520','SPAN','105');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPA','201','197520','SPAN','105');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPA','102','197520','SPAN','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPA','101','197520','SPAN','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPAN','199','197520','SPAN','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPC','101','199740','COM','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPE','219','199740','COM','325');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPE','201','199740','COM','204');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPE','10','199740','COM','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPE','100','199740','COM','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPE','101','199740','COM','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPE','101L','199740','COM','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPE','903','199740','COM','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('TEL','212','200740','CMPT','415');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('TEL','211','200740','CMPT','406');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('THE','261','199540','ENG','451');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('THE','209','200120','ENG','241');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('THE','161','200640','ENG','229');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('THE','109','200120','ENG','227');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('THE','105','199940','ENG','150');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('VIS','110','197520','ART','101');
