-- Generated by http://typexpert.net online CSV to SQL converter

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ACC','213','ACCT','350');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ACC','221L','ACCT','301');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ACC','221','ACCT','301');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ACC','221','ACCT','301');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ACC','221','ACCT','301');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ACC','221','ACCT','301');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ACC','201','ACCT','204');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ACC','204','ACCT','204');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ACC','104','ACCT','203');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ACC','194','ACCT','203');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ACC','103','ART','201');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ANT','102','ANTH','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','102','ART','366');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','254','ART','345');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','145','ART','324');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','123','ART','310');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','151','ART','240');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','140','ART','215');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','130','ART','207');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','226','ART','207');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','230','ART','207');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','113','ART','203');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','121','ART','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','204','ART','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','111','ART','201');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','101','ART','160');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','105','ART','145');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','150','ART','145');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','104','ART','125');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','104','ART','125');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','104','ART','111');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','120','ART','111');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','104','ART','111');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','112','ART','110');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','107','ART','105');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ART','110','ART','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('AST','131','PHYS','108');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('AST','131','PHYS','108');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('AST','131','PHYS','108');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('AST','131','PHYS','108');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BH','205','REST','335');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BH','103','SOC','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BH','207','EDUC','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','104','SOC','336');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','209','SOC','336');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','205','REST','335');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','242','CRJU','242');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','110','SOCW','230');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','262','CRJU','223');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','142','CRJU','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','142','CRJU','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','142','CRJU','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','142','CRJU','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','102','SOC','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','103','SOC','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','103','SOC','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','103L','SOC','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','214','ANTH','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','917','ANTH','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','206','ANTH','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','103','SOC','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','103','SOC','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','202','ANTH','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','207','EDUC','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','101','SOC','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','203','SOC','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BHS','230','SOC','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','203','BIOL','420');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','107','ENSC','360');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','107','ENSC','360');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','107','ENSC','360');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','107','BIOL','330');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','107','BIOL','330');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','107','BIOL','330');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','205','BIOL','320');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','920','ENSC','313');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','207','BIOL','312');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','212','BIOL','312');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','107','BIOL','237');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','107','BIOL','237');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','103','BIOL','237');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','103','BIOL','237');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','103','BIOL','237');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','103','BIOL','237');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','107','BIOL','237');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','204','BIOL','211');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','915','BIOL','210');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','210','BIOL','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','210','BIOL','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','210','BIOL','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','132','BIOL','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','210','BIOL','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','110','BIOL','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','131','BIOL','201');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','209','BIOL','201');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','209','BIOL','201');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','109','BIOL','201');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','122','HLTH','201');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','102','BIOL','131');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','106','BIOL','131');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','105','BIOL','130');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','101','BIOL','130');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','102L','BIOL','113');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','102LAB','BIOL','113');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','1019L','BIOL','112');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','101L','BIOL','112');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','101LAB','BIOL','112');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','1019','BIOL','110');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIO','221','ENSC','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIOL','102L','BIOL','113');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIOL','101L','BIOL','112');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BIOL','102','BIOL','111');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BOM','101','COM','100');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BRJ','206','CRJU','206');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BS','103','SOC','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','215','BUS','382');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','215','BUS','382');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','382N','BUS','382');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','216','BUS','381');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','216','BUS','381');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','125','BUS','380');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','215','BUS','380');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','215','BUS','380');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','233','BUS','380');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','241','BUS','380');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','208','FASH','361');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','107','BUS','340');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','131','PRLG','313');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','244','BUS','301');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','122','ACCT','204');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','110','CMPT','154');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','109','CMPT','152');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','112','CMPT','151');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','115','MUS','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','105','COM','110');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','100N','BUS','100');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','100N','BUS','100');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','104','BUS','100');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BUS','162','FASH','100');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('BYS','207','PHIL','233');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHE','232L','CHEM','216');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHE','232','CHEM','216');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHE','231','CHEM','215');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHE','231LAB','CHEM','213');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHE','232','CHEM','212');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHE','231','CHEM','211');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHE','116','CHEM','201');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHE','122','CHEM','132');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHE','121','CHEM','131');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHE','122L','CHEM','114');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHE','122LAB','CHEM','114');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHE','121L','CHEM','113');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHE','121LAB','CHEM','113');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHE','273','CHEM','112');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHE','101','CHEM','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHE','111','CHEM','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHEM','2263','CHEM','213');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHEM','116','INTD','213');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHEM','2262','CHEM','212');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHEM','2261','CHEM','211');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHEM','231','CHEM','211');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHEM','121','CHEM','131');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHEM','122','CHEM','131');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHEM','122L','CHEM','114');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHEM','111','CHEM','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHM','101','SOCW','230');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CHS','242','CRJU','242');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','212','CMPT','430');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','212','CMPT','430');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','212','CMPT','430');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','212','CMPT','430');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','117','CMPT','406');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','227','CMPT','321');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','126','CMPT','312');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','126','CMPT','312');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','126','CMPT','312');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','126','CMPT','312');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','214L','CMPT','310');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','214','CMPT','310');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','113','CMPT','236');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','215','CMPT','220');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','215','CMPT','220');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','111','CMPT','130');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','2130L','CMPT','130');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','111','CMPT','130');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','111','CMPT','130');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','111','CMPT','130');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','111','CMPT','130');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','111','CMPT','130');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','111','CMPT','130');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','111','CMPT','130');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','215','CMPT','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','215','CMPT','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','111','CMPT','103');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','111','CMPT','103');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','111','CMPT','103');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','111','CMPT','103');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','108','CMPT','103');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CIS','213','CMPT','103');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CLP','101','CRDV','100');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CLP','101','CRDV','100');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CLP','101','CRDV','100');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CLP','101','CRDV','100');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CLS','213','CMPT','130');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CMH','201','SOCW','330');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CMH','101','SOCW','230');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CMSC','412L','CMPT','412');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CMSC','121L','CMPT','121');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CMSC','120L','CMPT','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CO','140','COM','201');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','220','COM','396');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','250','COM','393');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','262','COM','393');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','233','COM','387');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','244','COM','321');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','245','COM','321');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','908','COM','321');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','244','MDIA','301');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','120','COM','289');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','120','COM','289');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','110','COM','287');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','249','COM','287');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','110','COM','287');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','207','COM','286');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','240','COM','285');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','110','MDIA','203');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','110','MDIA','203');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','201L','COM','201');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','140','COM','201');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','120','MDIA','201');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','120','MDIA','201');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','101','COM','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','101','COM','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','101','COM','100');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','203','COM','100');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('COM','101','COM','100');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CPS','231','CMPT','220');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CPS','231','CMPT','220');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CPS','141','CMPT','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CPS','141','CMPT','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CPS','231','CMPT','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CPS','231','CMPT','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CPS','100','CMPT','110');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CRJ','144','CRJU','305');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CRJ','263','CRJU','304');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CRJ','264','CRJU','303');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CRJ','201','CRJU','301');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CRJ','265','CRJU','250');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CRJ','206','CRJU','206');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('CRJ','141','CRJU','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('DAN','104','PHED','128');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('DAN','101','PHED','106');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('DAN','102','PHED','105');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('DTN','102','BIOL','225');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECN','105','ECON','150');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','224','ECON','442');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','218','BUS','402');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','121','ECON','305');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','105','ECON','150');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','115','ECON','150');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','202','ECON','104');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','202','ECON','104');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','201','ECON','103');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','201','ECON','103');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','106','ECON','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','201','ECON','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','201','ECON','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','208','ECON','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','216','ECON','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','102','ECON','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','202','ECON','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','202','ECON','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECO','215','ECON','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECON','102L','ECON','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECON','201','ECON','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECOO','12','ECON','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECOO','11','ECON','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ECOP','105','ECON','150');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('EN','12','ENG','116');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','209','ENG','382');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','309','ENG','382');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','208','ENG','363');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','224','ENG','353');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','224L','ENG','353');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','214','ENG','342');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','215','ENG','342');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','227','ENG','339');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','230','ENG','325');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','207','ENG','320');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','217','ENG','312');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','210','ENG','311');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','212','ENG','270');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','216','ENG','240');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','230','ENG','221');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','218','ENG','218');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','202','ENG','213');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','201','ENG','212');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','204','ENG','211');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','203','ENG','210');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','102','ENG','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','102','ENG','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','180','ENG','117');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','102','ENG','117');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','103','ENG','117');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','102','ENG','117');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','101','ENG','116');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENG','111','ENG','116');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ENT','1051','ACCT','203');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('FIN','2011','BUS','320');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('FIN','203','BUS','320');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('FRE','302','FREN','313');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('FRE','301','FREN','312');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('FRE','205','FREN','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('FRE','204','FREN','201');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('FRE','202','FREN','106');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('FRE','201','FREN','105');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('FRE','102','FREN','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('FRE','101','FREN','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('GERM','301','GERM','201');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('GERM','202','GERM','106');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('GERM','201','GERM','105');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('GERM','N201','GERM','105');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('GERM','102','GERM','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('GERM','101','GERM','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('GOV','219','POSC','273');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('GOV','221','POSC','252');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('GOV','201','POSC','243');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('GOV','122','POSC','211');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('GOV','121','POSC','110');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('GOV','151','PRLG','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('GOVT','121','POSC','110');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HED','134','HLTH','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HED','123L','PHED','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HIS','206','HCMPTT','274');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HIS','914','HCMPTT','271');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HIS','217','HCMPTT','270');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HIS','207','HCMPTT','260');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HIS','221','HCMPTT','248');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HIS','209','HCMPTT','234');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HIS','214','HCMPTT','230');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HIS','104','HCMPTT','227');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HIS','114','HCMPTT','227');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HIS','273','HCMPTT','227');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HIS','103','HCMPTT','226');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HIS','121','POSC','110');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HIS','102','HCMPTT','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HIS','108','HCMPTT','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HIST','104','HCMPTT','227');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HIST','108','HCMPTT','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HLTH','202N','HLTH','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HMS','263','CRJU','304');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HMS','264','CRJU','303');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HMS','242','CRJU','242');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HMS','262','CRJU','223');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('HMS','141','CRJU','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('IS','310','CMPT','321');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ITA','202','ITAL','106');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ITA','201','ITAL','105');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ITA','101','ITAL','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ITL','205','ITAL','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ITL','204','ITAL','201');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ITL','202','ITAL','106');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ITL','201','ITAL','105');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ITL','102','ITAL','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('ITL','101','ITAL','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('LAW','212','BUS','381');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('LITL','102','ITAL','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MA','102','MATH','130');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAR','200','BUS','340');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','223','MATH','343');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','224','MATH','321');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','217','MATH','310');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','140','MATH','250');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','214','MATH','250');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','222','MATH','242');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','107','EDUC','241');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','107','EDUC','241');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','221','MATH','241');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','221','MATH','241');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','215','MATH','210');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','118','MATH','130');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','115','MATH','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','185','MATH','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','185','MATH','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','185','MATH','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','185','MATH','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','125','MATH','115');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','221','MATH','115');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','221','MATH','115');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','101','MATH','110');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','109L','MATH','110');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','109','MATH','110');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','110','MATH','108');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MAT','184','MATH','108');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MATH','122','MATH','242');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MATH','222','MATH','222');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MATH','121','MATH','221');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MATH','118','MATH','130');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MATH','130','MATH','130');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MATH','125L','MATH','115');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MATH','110','MATH','108');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MGT','205','BUS','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MLT','202','BIOL','421');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MUS','241','MUS','410');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MUS','211','MUS','351');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MUS','221','MUS','301');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MUS','136','MUS','234');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MUS','137','MUS','234');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MUS','117','MUS','231');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MUS','116','MUS','220');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MUS','210','MUS','213');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MUS','104','MUS','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MUS','115','MUS','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MUS','122','MUS','111');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MUS','121','MUS','110');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MUS','142','MUS','108');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MUS','141','MUS','107');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('MUS','135','MUS','106');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('OFT','232','CMPT','152');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('OFT','108','CMPT','151');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('OFT','231','CMPT','151');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PAL','290','CRJU','496');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PAL','240','PRLG','422');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PAL','220','PRLG','420');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PAL','230','PRLG','380');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PAL','210','PRLG','311');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PAL','120','PRLG','210');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PAR','230','BIOL','497');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PAR','220','BIOL','496');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PAR','120','BIOL','495');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PAR','206','ATHT','310');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PAR','201','ATHT','205');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PE','123','PHED','133');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PED','116','PHED','147');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PED','116','PHED','147');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PED','116','PHED','147');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PED','116','PHED','147');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PED','180','PHED','139');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PED','170','PHED','138');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PED','123','PHED','133');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PED','132','PHED','130');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PED','144','PHED','128');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PED','124','PHED','127');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PED','103','PHED','124');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PED','109','PHED','123');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PED','131','PHED','120');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PED','141','PHED','106');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHI','205','PHIL','300');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHI','205','PHIL','300');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHI','203','REST','209');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHI','107','PHIL','203');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHI','207','PHIL','203');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHI','205','PHIL','200');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHI','205','PHIL','200');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHI','204','PHIL','103');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHI','201','PHIL','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHI','201','PHIL','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHIL','203','REST','209');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHS','111','ENSC','211');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHS','111','ENSC','211');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHS','111','ENSC','211');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHS','111','ENSC','211');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHS','203','REST','209');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHS','114','CHEM','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHS','103','ENSC','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHY','251','PHYS','221');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHY','122411','PHYS','214');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHY','122L','PHYS','214');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHY','122','PHYS','214');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHY','152L','PHYS','214');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHY','121','PHYS','213');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHY','151L','PHYS','213');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHY','121L','PHYS','213');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHY','122','PHYS','212');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHY','122410','PHYS','212');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHY','152','PHYS','212');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHY','121','PHYS','211');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHY','151','PHYS','211');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHY','107','PHIL','203');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PHYS','121','PHYS','211');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PLS','201','CRJU','301');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PLS','205','CRJU','206');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('POS','219','POSC','273');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('POS','122','POSC','211');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('POS','121','POSC','110');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','203','SOCW','345');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','236','SOCW','345');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','102','SOCW','330');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','102','SOCW','330');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','222','PSYC','321');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','204','PSYC','318');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','203','PSYC','317');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','221','PSYC','317');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','209','PSYC','301');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','205','PSYC','220');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','206','PSYC','220');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','114','PSYC','215');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','124','PSYC','215');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','134','PSYC','215');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','901','PSYC','209');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','211','PSYC','208');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','235','PSYC','207');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','210','PSYC','206');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','201','PSYC','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','101','PSYC','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','111','PSYC','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSY','111L','PSYC','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSYC','134','PSYC','215');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSYC','101','PSYC','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('PSYC','111','PSYC','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('REA','100','LERN','105');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('REA','103','LERN','105');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('REA','105','LERN','105');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('RET','211','FASH','400');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('RET','101','BUS','340');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('RET','204','FASH','285');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('RET','106','FASH','265');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SCS','264','CRJU','304');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SCS','263','CRJU','303');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SCS','242','CRJU','242');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SCS','262','CRJU','223');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SCS','134','PSYC','215');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SCS','142','CRJU','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SCS','141','CRJU','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SO','207','CRJU','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SOC','202','SOC','336');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SOC','202','SOC','336');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SOC','101','SOC','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SOC','113','SOC','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SOC','203','SOC','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SOCI','101','SOC','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPA','320','SPAN','210');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPA','302','SPAN','202');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPA','301','SPAN','201');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPA','2040','SPAN','106');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPA','202','SPAN','106');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPA','2030','SPAN','105');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPA','201','SPAN','105');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPA','102','SPAN','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPA','101','SPAN','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPAN','199','SPAN','102');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPC','101','COM','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPE','219','COM','325');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPE','201','COM','204');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPE','10','COM','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPE','100','COM','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPE','101','COM','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPE','101L','COM','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('SPE','903','COM','101');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('TEL','212','CMPT','415');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('TEL','211','CMPT','406');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('THE','261','ENG','451');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('THE','209','ENG','241');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('THE','161','ENG','229');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('THE','109','ENG','227');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('THE','105','ENG','150');

INSERT INTO transfer (d_subject, d_course_num, m_subject, m_course_num) VALUES ('VIS','110','ART','101');
